services:
  redis:
    image: docker.io/redis:7.2.4
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${HOME}/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - shenma

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_DB: "codebase_indexer"
      POSTGRES_USER: "shenma"
      POSTGRES_PASSWORD: "shenma"
    volumes:
      - ${HOME}/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    networks:
      - shenma

networks:
  shenma:
    driver: bridge
